#+TITLE: Basics

** Vocabulary
*** Vocabulary
Let's establish some vocabulary first

 - =C=: Control
   - E.g. =C-x C-e= means =Ctrl+X (then) Ctrl+E=
 - =M=: Meta key, usually =Alt=
   - E.g. =M-:= means =Alt+Shift+;=
 - Evaluate an expression: =M-:=
 - Running a command: =M-x=

*** Windows

A window is a visual interface that displays different types of buffers. These can be split between different files.

*** Buffers

Buffers are reproductions of an actual file or a temporary file or simply a message. They are often displayed in windows. They do not need to be visible in order to be opened. You may switch buffers

- =switch-to-buffer=
- =compleseus-switch-to-buffer=
- =SPC b b= (Spacemacs)

If you wish to abort, you may either run =C-g= or =ESC=

** Execute Commands

Split window vertical
  - =split-window-right=
  - =SPC w v= (Spacemacs)

Split window horizontal
  - =split-window-below=
  - =SPC w s= (Spacemacs)

Close window
  - =delete-window=
  - =SPC w d= (Spacemacs)

Close window
  - =delete-window=
  - =SPC w d= (Spacemacs)

Split window in 4 grid
  - =window-split-grid=
  - =SPC w 4= (Spacemacs)

Resize your window
  - =shrink-window-horizontally=
  - =SPC w [= (Spacemacs)
  - =C-x {= (Vanilla)
  - =enlarge-window-horizontally=
  - =SPC w ]= (Spacemacs)
  - =C-x }= (Vanilla)

Under Spacemacs, it installs the package =winum= by default, which then allows one to jump between different windows by numbered IDs. It can be run using:

  - =winum-select-window-{number}= (e.g. =winum-select-window-4=)
  - =SPC {number}= / =M-{number}= (e.g. =SPC 4= or =M-4=) (Spacemacs)
  - =M-m {number}= (e.g. =M-m 4=) (Vanilla)


** Create a new file

We can create new files by finding a file. When we "find a file" that does not exist, you end up creating a new file.

- =find-file=
- =SPC f f=  (Spacemacs)
- =C-x C-f= (Vanilla)

This will open a new buffer. The file will not be created until you save.

* Save Files

In order to save your file, you can run the following command:

- =save-buffer=
- =SPC f s=
- =C-x C-s= (Vanilla)
- =:w= (using Evil)

** Evil Mode

Emacs is not a text editor. It is a programmable environment with a Lisp interpreter. It also happens to have a text editor in it.

People write Elisp code in forms of functions, operations, and compile them into packages.

If you entered the same responses showed on the top of this document, you should have =evil= mode set as default. Therefore, at this point, you should be able to use Vim keybindings in order to edit your files.
