#+TITLE: Org-Journal


** Introduction

Org-Journal is an incredibly powerful way to keep your own diary notes. This can be used for personal reasons, but also for work reasons. Like Org-Roam, the entire system is stored in flat files, and can easily be recovered by simply having those files.

** Installation

*** Spacemacs

In Spacemacs, go to =dotspacemacs/layers= > =dotspacemacs-configuration-layers=, and set the =org-enable-org-journal-support= to true =t=. If you have only activated =org= as a base layer, you'll have to create parenthesis. Then reload your configuration file via =SPC f e R=.

#+BEGIN_SRC elisp
  (defun dotspacemacs/layers ()
    ...
    dotspacemacs-configuration-layers
    '(
      (org
       :variables
       org-enable-org-journal-support t
       )
      )
    ...
    )
#+END_SRC

Next, setup the variable =org-journal-dir= to the location of the journal files.

#+BEGIN_SRC elisp
(setq org-journal-dir "~/path/to/journal/")
#+END_SRC

*** TODO Doom Emacs

In order to add Org-Journal, you can simply add the =+journal= to the =org= entry in your =init.el= file.

#+begin_src elisp
(doom!
   (org
    +journal
    )
 )

#+end_src

Next, setup the variable =org-journal-dir= to the location of the journal files.

#+BEGIN_SRC elisp
(setq org-journal-dir "~/path/to/journal/")
#+END_SRC

** Usage

*** New Entry

In order to add a new automatically set entry for today and now, you can run the following command:

  - =org-journal-new-entry=
  - =SPC a o j i= (Spacemacs)
  - =SPC n j j= (Doom Emacs)

This will do the following:
  - If no file exists for the current date, it will create a new file and with the current time
  - If a file does exist, it will create a new heading with the current time

Every time you create a new date in a new day, your last saved tasks will automatically move to the new note. This becomes extremely useful to move your forgotten tasks forward.

*** Scheduled Entry

If you wish to create a scheduled entry, you may run the command below. It will then open a =org-calendar= that you can navigate via =M-{hjkl}= to select your date.

  - =org-journal-new-scheduled-entry=
  - =SPC a o j t= (Spacemacs)
  - =SPC n j J= (Doom Emacs)

** Customization

There are may different ways you can customize it later. Below are some variables you may set:

  - =org-journal-file-format=
  - =org-journal-date-prefix=
  - =org-journal-date-format=
  - Many more...

It's recommended to read some of the documentation on it.

** Appendix

*** File Naming Format

In addition to saving the files on =org-journal-dir=, you may wish to save the files in a specific format. You may set it as:

#+begin_src elisp
org-journal-file-format "%Y-%m-%d.org"
#+end_src

For example, on Spacemacs, you may set it via:

#+begin_src elisp
  dotspacemacs-configuration-layers
  '(
    (org :variables
         org-journal-dir "/path/to/journal"
         org-journal-file-format "%Y-%m-%d.org"
    )
#+end_src


*** Date Format

Within the org file itself, you may wish to setup the header of the section which represents the date to show in a specific format. Therefore, you may set it via the format below (as an example) to yield "Monday, 2022-02-31"

#+begin_src elisp
org-journal-date-format "%a, %Y-%m-%d"
#+end_src

For example, on Spacemacs, you may set it via:

#+begin_src elisp
  dotspacemacs-configuration-layers
  '(
    (org :variables
         org-journal-dir "/path/to/journal"
         org-journal-date-format "%a, %Y-%m-%d"
    )
#+end_src
*** LaTeX Header

If you know you will want your Org-Journal files to have specific settings for LaTeX exporting, you may edit the =org-journal-file-header=. This may be set via:

#+begin_src elisp
org-journal-file-header "#+LATEX_HEADER: \\usepackage[margin=0.5in]{geometry}\n#+LATEX_HEADER: \\usepackage{bm}\n" ;; For more styles, run $ pygmentize -L styles
#+end_src

As an example, you may add:

#+begin_src elisp
  dotspacemacs-configuration-layers
  '(
    (org :variables
         org-journal-dir "/path/to/journal"
         org-journal-file-header "#+LATEX_HEADER: \\usepackage[margin=0.5in]{geometry}\n#+LATEX_HEADER: \\usepackage{bm}\n#+LATEX_HEADER: \\usepackage{minted}\n#+LATEX_HEADER: \\usemintedstyle{emacs}\n#+LATEX_HEADER: \\usepackage[ttscale=0.7]{libertine}\n#+LATEX_HEADER: \\usepackage{tcolorbox}\n#+LATEX_HEADER: \\usepackage{xcolor}\n#+LATEX_HEADER: \\newtcolorbox[auto counter, number within=section]{fancyquotes}[1][]{colframe=white!80!black, colback=black!20, boxrule=0.5mm, #1}\n#+LATEX_HEADER: \\usepackage[inkscapelatex=false]{svg}\n#+LATEX_HEADER: \\usepackage{colortbl}\n#+LATEX_HEADER: \\newcommand{\\cc}[1]{\\cellcolor{#1}}\n" ;; For more styles, run $ pygmentize -L styles
    )
#+end_src

Note: The example above may require more setup on your own operating system.
