#+TITLE: Installation

For this tutorial, we will be using Spacemacs as our entry point to using Emacs. Please follow the steps below to get Spacemacs setup for your system.

** Windows

*** Get the Installer

If you use Chocolatey, you may install it via

#+BEGIN_SRC shell
choco install emacs
#+END_SRC

Otherwise, the easiest method is to go to the [[https://www.gnu.org/software/emacs/download.html][GNU Emacs Download page]] and get to the file server for a [[http://ftpmirror.gnu.org/emacs/windows][nearby GNU mirror]]. You may choose any version. For this guide, select =emacs-30/= and then select =emacs-30.2.installer.exe=. Next, run the installer.

  - Click on =Next >=, then read their copyleft license, click on =OK=. 
  - Next, choose a destination folder. You may leave it at =C:\Program Files\Emacs=.
  - Next, you may create a Start Menu folder.
  - Once ready, click on =Install=

*** Setting Up Dotfiles

Unix systems often use dotfiles for their configuration. If you use a tiling window manager, you're likely extremely familiar with this concept. Dotfiles are effectively ASCII files that have text configurations for an application or for an entire system. It therefore becomes very easy to edit simple files and change entire configurations without having to go through setting dialogs.

By default, Emacs on Windows looks for configurations in the =%AppData%= directory (i.e., =C:\Users\USERNAME\AppData\Roaming=). This can be changed by setting an explicit =HOME= environment variable, which results in GNU Emacs to look in that location instead, which matches with Unix behaviors.

  - Run the command (i.e., =Win+R=) =sysdm.cpl=
  - Open the =Advanced= tab
  - Click on the =Environment Variables...= button
  - Under the =Environment Variables= window and under the =User variables for USERNAME=, click on =New...= button
  - Under =New User Variable= window, enter the following values:
    + Variable name: =HOME=
    + Variable value: =C:\Users\USERNAME=
  - Click on =OK= to close the =New User Variable=, =OK= to close the =Environment Variables=, then =OK= to close the =System Properties= window.

Clean up any previous existing configuration directories by removing =.emacs.d= and =.emacs= from the =C:\Users\USERNAME= directory (i.e., =$env:USERPROFILE= in PowerShell or =%USERPROFILE%= in Command Prompt).

*** Installing Spacemacs

Now that the configuration directory is cleared, bring in the default configurations from Spacemacs

#+BEGIN_SRC shell
# In PowerShell
git clone https://github.com/syl20bnr/spacemacs $env:USERPROFILE/.emacs.d

# In Command Prompt
git clone https://github.com/syl20bnr/spacemacs %USERPROFILE%/.emacs.d
#+END_SRC

At this point, Spacemacs will be Installed. 

** GNU/Linux

*** Arch Linux

If using an Arch-based distribution, you can just install the =emacs= package. Or you may look through [[https://wiki.archlinux.org/title/Emacs][Arch Wiki's Emacs page]].


*** Ubuntu

The following is the best way to install Emacs on an Ubuntu system, taken from [[https://gist.github.com/shanbhardwaj/866f20e98303379ca8bfbe2f0c5b7a87][Shanbhardwaj's Gist]]. (Copied on 2026-06-15). The reason this is used is because a lot of the public repositories have outdated Emacs versions.

#+BEGIN_SRC shell
# Setting up Emacs in our source directory
mkdir -p ~/src && cd ~/src
git clone --depth 1 --branch emacs-30 git://git.savannah.gnu.org/emacs.git
cd emacs
git checkout emacs-30

# Enable development libraries and update apt cache
# for Ubuntu >= 24.04
sudo sed -i 's/^Types: deb$/Types: deb deb-src/' /etc/apt/sources.list.d/ubuntu.sources && apt update

# for ubuntu < 24, uncomment and use the following
# sudo sed -i 's/# deb-src/deb-src/' /etc/apt/sources.list && apt update

# Install necessary dependencies
sudo apt build-dep -y emacs \
  && sudo apt install libtree-sitter-dev

# Generate the configure file
./autogen.sh

# Configure Emacs with desired options
# --with-ctags --with-dbus --with-debug --with-mailutils --with-x11 --with-xwidgets
./configure --with-imagemagick

# Compile with 4 cores
make -j4 bootstrap

# Verify the version
./src/emacs --version

# Optionally, test things by launching Emacs without any configuration
./src/emacs -Q

# When things look good, install Emacs system-wide
sudo make install
#+END_SRC


** First Startup in Spacemacs

Your first boot up of Spacemacs will yield a few questions. Enter the following answers:

1. What is your preferred editing style? (*v*im, *e*macs, *h*ybrid)
  - =v= / Vim

2. What distribution of spacemacs would you like to start with? (*s*pacemacs, spacemacs-*b*ase)  
  - =s= / spacemacs

Depending on your system, it may try to install 126 packages and may struggle. If the system may be dealing with proxies, see below:

** Handling Proxies

It is possible that your system may exist behind a proxy. For that, edit the file =C:\Users\USERNAME\.spacemacs=, go to line 84, and inside the =dotspacemacs/init= function, add the following (according to your organization):

#+BEGIN_SRC elisp
(defun dotspacemacs/init ()
  ;; Add proxies
  (setq url-proxy-services
    '(("http" . "proxy.lan.organization.com:8080")
      ("https" . "proxy.lan.organization.com:8080")
    )
  )
  ...
)
#+END_SRC

This will enable GNU Emacs to fetch all of its default packages.